# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  DRV_DEPS_QT5_LOCATION: '${{ github.workspace }}/qt/'

jobs:
  install_Qt5:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    runs-on: windows-latest
    steps:
    - name: Init cache QT
      id: init_qt_cache
      uses: actions/cache/@v3
      with:
        path: ${{ env.DRV_DEPS_QT5_LOCATION }}
        key: ${{ runner.os }}-qt-5.15.2

    - name: MSVC
      uses: ilammy/msvc-dev-cmd@v1.4.1
      
    - name: Install Qt
      if: steps.init_qt_cache.outputs.cache-hit != 'true'
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}/qt/'
        install-deps: 'true'
        modules: 'qtcharts qtwebengine qtquick3d'
        archives: 'qtbase qtsvg'
        cache: 'false'
        cache-key-prefix: 'install-qt-action'
        setup-python: 'true'
        set-env: 'true'
        tools-only: 'false'
        aqtversion: '==3.1.*'
        py7zrversion: '==0.20.*'
        extra: '--external 7z'

  setup_CMake:
    needs: install_Qt5
    runs-on: windows-latest
    steps:
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.34'
    - name: MSYS2
      uses: msys2/setup-msys2@v2

    - shell: msys2 {0}
      run: |
        pacman -S --needed --noconfirm \
          mingw-w64-x86_64-autotools \
          mingw-w64-x86_64-cmake \
          mingw-w64-x86_64-glew \
          mingw-w64-x86_64-libarchive \
          mingw-w64-x86_64-make \
          mingw-w64-x86_64-meson \
          mingw-w64-x86_64-python-pip \
          mingw-w64-x86_64-python-psutil \
          mingw-w64-x86_64-toolchain \
          bison \
          flex \
          git \
          nasm \
          p7zip \
          patch \
          unzip \
          zip

  build:
    runs-on: windows-latest
    needs: setup_CMake
    steps:
    - name: Init cache QT
      id: init_qt_cache
      uses: actions/cache/@v3
      with:
        path: ${{ env.DRV_DEPS_QT5_LOCATION }}
        key: ${{ runner.os }}-qt-5.15.2

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        cd ${{env.DRV_DEPS_QT5_LOCATION}}/Qt/5.15.2
        ls
        cmake -S . -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DRV_DEPS_QT5_LOCATION=D:\a\OpenRV\Qt\5.15.2\msvc2019_64\
      
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -DRV_DEPS_QT5_LOCATION=D:\a\OpenRV\Qt\5.15.2\msvc2019_64\

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
